language: node_js
node_js:
    - "0.12"
    - "4"
    - "5"
    - "6"

env:
    - SUITE=unit
    - SUITE=lint

matrix:
    exclude:
        - node_js: "0.12"
          env: SUITE=lint

script: npm run $SUITE

after_success:
    - ./node_modules/.bin/jscoverage lib lib-cov
    - ./node_modules/.bin/mocha -R mocha-lcov-reporter --recursive tests/unit | ./node_modules/.bin/coveralls
