language: node_js
node_js:
    - "stable"
    - "0.12"
    - "4"

branches:
    only:
        - master
        - /^v\d+\.\d+/

after_success:
    - ./node_modules/.bin/jscoverage lib lib-cov
    - ./node_modules/.bin/mocha -R mocha-lcov-reporter --recursive tests/unit | ./node_modules/.bin/coveralls
